version: '3.1'
services:
  db:
    platform: linux/x86_64
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

volumes:
  database: